package net.geforcemods.teleportals;

import java.util.Arrays;

import net.geforcemods.teleportals.handlers.ForgeEventHandler;
import net.geforcemods.teleportals.network.ConfigurationHandler;
import net.geforcemods.teleportals.network.ServerProxy;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.config.Configuration;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper;

@Mod(modid=Teleportals.MODID, name=Teleportals.NAME, version=Teleportals.VERSION, acceptedMinecraftVersions = "[" + Teleportals.MCVERSION + "]", dependencies=Teleportals.FORGEVERSION, guiFactory="net.geforcemods.teleportals.gui.TeleportalGuiFactory")
@SuppressWarnings("static-access")
public class Teleportals {
	
	public static final String MODID = "teleportals";
	public static final String NAME = "Teleportals";
	public static final String VERSION = "0.8.0.0";
	public static final String MCVERSION = "1.7.10";
	public static final String FORGEVERSION = "required-after:Forge@[10.13.4.1558,)";
	
	public static boolean isDebugMode;
	
	@SidedProxy(clientSide = "net.geforcemods.teleportals.network.ClientProxy", serverSide = "net.geforcemods.teleportals.network.ServerProxy")
	public static ServerProxy serverProxy;
	
	@Instance("teleportals")
	public static Teleportals instance = new Teleportals();
		
	public static ForgeEventHandler eventHandler = new ForgeEventHandler();
	
	public static ConfigurationHandler configHandler = new ConfigurationHandler();
	
	public static SimpleNetworkWrapper network;
	
	public static Configuration configFile;
	
	public static Block portal;
	public static Block advancedPortal;
	public static Block fillerPortal;
	
	public static Item portalMinecart;
	
	public static int beaconTeleportationRange;
	public static int minecartTeleportationRange;

	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event){
		this.configHandler.setupConfiguration(event);
		this.configHandler.setupHandlers(event);
		this.configHandler.setupAdditions(event);
		
		Teleportals.network = NetworkRegistry.INSTANCE.newSimpleChannel(Teleportals.MODID);
		this.configHandler.setupPackets(Teleportals.network);
		
		setupMCModInfo(event);
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event){		
		this.configHandler.setupEntityRegistry();
		serverProxy.registerProxy();
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event){
		MinecraftForge.EVENT_BUS.register(Teleportals.eventHandler);
	}
	
	private void setupMCModInfo(FMLPreInitializationEvent event){
		ModMetadata modMeta = event.getModMetadata();
        modMeta.authorList = Arrays.asList(new String[] {
            "Geforce", "The_Pastmaster"
        });
        modMeta.autogenerated = false;
        modMeta.credits = "Thanks to The_Pastmaster for giving me the idea.";
        modMeta.description = "Adds utility transport portals into Minecraft!";
        modMeta.url = "http://geforcemods.net";
        modMeta.logoFile = "/logo.png";
	}
	
	public static void log(String par1){
		log(par1, false);
	}
	
	public static void log(String par1, boolean isSevereError){
		if(isDebugMode){
			System.out.println(isSevereError ? "{" + Teleportals.NAME + "} ***SEVERE*** : " + par1 : "[" + Teleportals.NAME + "] [" + FMLCommonHandler.instance().getEffectiveSide() + "] " + par1);
		}
	}

}
